<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>2_stats_spectrum.utf8.md</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' || rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 52px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h2 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h3 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h4 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h5 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h6 {
  padding-top: 57px;
  margin-top: -57px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li>
  <a href="1_math.html">математика и статистика</a>
</li>
<li>
  <a href="2_stats_spectrum.html">статистика и опять спектр</a>
</li>
<li>
  <a href="3_vowels.html">гласные</a>
</li>
<li>
  <a href="4_sonorants.html">сонорные</a>
</li>
<li>
  <a href="5_obstruents.html">шумные</a>
</li>
<li>
  <a href="6_prosody.html">просодия</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->
<style>
.main-container {
  margin-left: 0;
  margin-right: 0;
}
</style>

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>




</div>


<div id="section" class="section level1">
<h1>1. Регрессионный анализ</h1>
<p>Для тех, кто хочет следить за кодом, вот загруженные библиотеки:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="co"># это стиль для ggplot (можно игнорировать эту команду)</span></span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="kw">theme_set</span>(<span class="kw">theme_bw</span>()<span class="op">+</span></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="st">            </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>))) </span></code></pre></div>
<p>В качестве примера я использую данные из работы [Huttenlocher, Vasilyeva, Cymerman, Levine 2002], в которой авторы проанализировали 46 пар матерей и детей (возрастом от 47 до 59 месяцев, средний возраст … а пасчитайте сами!). Они записали и затранскрибировали 2 часа каждого дня ребенка. Потом они посчитали количество именных групп на предложение у матерей и ребенка. Данные можно скачать командой: <code>np_acquisition &lt;- read.csv("https://raw.githubusercontent.com/agricolamz/2019_PhonDan/master/data/Huttenlocher.csv")</code></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>np_acquisition &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/agricolamz/2019_PhonDan/master/data/Huttenlocher.csv&quot;</span>)</span>
<span id="cb2-2"><a href="#cb2-2"></a>np_acquisition</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["child"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["mother"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"1.48","2":"1.20"},{"1":"1.48","2":"1.40"},{"1":"1.60","2":"1.45"},{"1":"1.58","2":"1.50"},{"1":"1.57","2":"1.51"},{"1":"1.16","2":"1.52"},{"1":"1.40","2":"1.59"},{"1":"1.48","2":"1.58"},{"1":"1.73","2":"1.59"},{"1":"1.71","2":"1.58"},{"1":"1.73","2":"1.60"},{"1":"1.59","2":"1.61"},{"1":"1.77","2":"1.63"},{"1":"1.74","2":"1.64"},{"1":"1.73","2":"1.65"},{"1":"1.58","2":"1.66"},{"1":"1.49","2":"1.66"},{"1":"1.50","2":"1.66"},{"1":"1.29","2":"1.65"},{"1":"1.23","2":"1.81"},{"1":"1.40","2":"1.85"},{"1":"1.54","2":"1.70"},{"1":"1.82","2":"2.22"},{"1":"2.12","2":"2.18"},{"1":"1.98","2":"2.10"},{"1":"2.02","2":"2.11"},{"1":"1.92","2":"1.92"},{"1":"1.89","2":"1.93"},{"1":"1.87","2":"1.94"},{"1":"1.87","2":"1.76"},{"1":"1.86","2":"1.85"},{"1":"1.75","2":"1.91"},{"1":"1.75","2":"1.89"},{"1":"1.76","2":"1.70"},{"1":"1.78","2":"1.68"},{"1":"1.70","2":"1.91"},{"1":"1.55","2":"1.92"},{"1":"1.74","2":"1.98"},{"1":"1.66","2":"2.03"},{"1":"1.72","2":"1.68"},{"1":"1.59","2":"1.72"},{"1":"1.61","2":"1.73"},{"1":"1.59","2":"1.74"},{"1":"1.59","2":"1.76"},{"1":"1.68","2":"1.81"},{"1":"1.58","2":"1.84"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div id="section-1" class="section level2">
<h2>1.1 Линейная регрессия</h2>
<p>Представим себе, что мы хотим научиться предсказывать количество именных групп у ребенка на основании количества именных групп у матери.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>np_acquisition <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(mother, child))<span class="op">+</span></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;данные [Huttenlocher, Vasilyeva, Cymerman, Levine 2002]&quot;</span>)</span></code></pre></div>
<p><img src="2_stats_spectrum_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Простейшая статистическая модель будет выглядеть следующим образом:</p>
<p><span class="math display">\[y_i = \beta_0 + e_i\]</span></p>
<ul>
<li><span class="math inline">\(y_i\)</span> — множество ответов</li>
<li><span class="math inline">\(\beta_0\)</span> — некоторая константа</li>
<li><span class="math inline">\(e_i\)</span> — остатки/ошибки регресиионной модели</li>
</ul>
<p>Так как любая регрессионная модель стремиться улучшить свои предсказания, лучшим коэфециентом <span class="math inline">\(k\)</span> будет тот, при котором <span class="math inline">\(e_i\)</span> будут минимальны. В нашей простой модели — это понятное дело будет среднее:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>np_acquisition <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(mother, child))<span class="op">+</span></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="kw">aes</span>(<span class="dt">yintercept =</span> (<span class="kw">mean</span>(mother))), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>)<span class="op">+</span></span>
<span id="cb4-4"><a href="#cb4-4"></a><span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;данные [Huttenlocher, Vasilyeva, Cymerman, Levine 2002]&quot;</span>)</span></code></pre></div>
<p><img src="2_stats_spectrum_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><span class="math display">\[child_j = mean(child) + e_j\]</span></p>
<p>Если мы хотим включить переменную <code>mother</code> в нашу регрессию, то мы это можем сделать используя формулу прямой:</p>
<p><span class="math display">\[y_j = \beta_0 + \beta_1\times x_j + e_j\]</span></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>np_acquisition <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(mother, child))<span class="op">+</span></span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)<span class="op">+</span></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span></span>
<span id="cb5-5"><a href="#cb5-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">caption =</span> <span class="st">&quot;данные [Huttenlocher, Vasilyeva, Cymerman, Levine 2002]&quot;</span>)</span></code></pre></div>
<p><img src="2_stats_spectrum_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Т. е. формула применительно к нашим данным выглядит следующим образом:</p>
<p><span class="math display">\[child_j = \beta_0 + \beta_1\times mother_j + e_j\]</span></p>
<p>В R это делается при помощи функции <code>lm</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="kw">lm</span>(child<span class="op">~</span>mother, <span class="dt">data =</span> np_acquisition)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = child ~ mother, data = np_acquisition)
## 
## Coefficients:
## (Intercept)       mother  
##      0.7038       0.5452</code></pre>
<p>Теперь мы можем полностью записать формулу:</p>
<p><span class="math display">\[child_j = 0.7038 + 0.5452 \times mother_j + e_j\]</span></p>
<p>Результаты регрессии можно записать в переменную, а потом посмотреть даже статистическую значимость каждого из полученных коэффициентов:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(child<span class="op">~</span>mother, <span class="dt">data =</span> np_acquisition)</span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = child ~ mother, data = np_acquisition)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.46058 -0.08925  0.01071  0.13333  0.22770 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.7038     0.2051   3.432  0.00132 ** 
## mother        0.5452     0.1166   4.676 2.79e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1627 on 44 degrees of freedom
## Multiple R-squared:  0.332,  Adjusted R-squared:  0.3168 
## F-statistic: 21.86 on 1 and 44 DF,  p-value: 2.789e-05</code></pre>
<p>На что смотреть:</p>
<ul>
<li>на статистическую значимость коэффициентов</li>
<li>Adjusted R-квадрат</li>
<li>на p-value всей модели</li>
</ul>
<p>Теперь мы можем предсказывать! Правдо не обязательно все руками вбивать в формулу, например, для значения <code>mother = 1.69</code>:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="kw">predict</span>(fit, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">mother =</span> <span class="fl">1.69</span>))</span></code></pre></div>
<pre><code>##        1 
## 1.625153</code></pre>
<blockquote>
<p>🤔 Скачайте <a href="https://raw.githubusercontent.com/agricolamz/2019_PhonDan/master/data/chekhov.csv">датасет с параметрами рассказов А. П. Чехова</a>: количество уникальных слов, длина рассказа. Постройте регрессионную модель предсказывающую количество уникальных слов на основе длины рассказа. Какой получился интерсепт (с точностью до 4 знаков после запятой)?</p>
</blockquote>
<form name="FormOne" onsubmit="return validateFormOne()" method="post">
<input type="text" name="answerOne"> <input type="submit" value="check">
</form>
<p><br></p>
<blockquote>
<p>🤔 Какой получился коэффициент при переменной длина рассказа (с точностью до 4 знаков после запятой)?</p>
</blockquote>
<form name="FormTwo" onsubmit="return validateFormTwo()" method="post">
<input type="text" name="answerTwo"> <input type="submit" value="check">
</form>
<p><br></p>
<blockquote>
<p>🤔 Что полученная модель предсказывает для рассказа размером 855 слов (с точностью до 4 знаков после запятой)?</p>
</blockquote>
<form name="FormThree" onsubmit="return validateFormThree()" method="post">
<input type="text" name="answerThree"> <input type="submit" value="check">
</form>
<p><br></p>
</div>
<div id="section-2" class="section level2">
<h2>1.2 Категориальные переменные</h2>
<p>А что если одна из переменных у нас категориальная? В таком случае вводятся <em>dummy-переменные</em>. Рассмотрим наш вчерашний пример <a href="https://raw.githubusercontent.com/agricolamz/2019_PhonDan/master/data/Hau.2007.csv">из [Hau 2007]</a>:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>homo &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/agricolamz/2019_PhonDan/master/data/Hau.2007.csv&quot;</span>)</span></code></pre></div>
<p>Попробуем предсказать длительность s на основании ориентации спикера. Для этого в регрссию вводят так-называемые <em>dummy-переменные</em>. Dummy-переменные принимают лишь два значения либо 1, либо 0. В нашем случае 1 — гомосексуал, 0 — гетеросексуал.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>homo <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(orientation, s.duration.ms))<span class="op">+</span></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="2_stats_spectrum_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>В таком случае наша формула примет следующий вид:</p>
<p><span class="math display">\[y_j = \beta_0 + \beta_1\times x + e_j\]</span></p>
<p><span class="math display">\[s\_duration_j = \beta_0 + \beta_1\times orientation_j + e_j\]</span></p>
<p>При описании гомосексуалов переменная <span class="math inline">\(orientation = 1\)</span>, тогда модель принимает вид: <span class="math display">\[s\_duration_j = \beta_0 + \beta_1\times orientation_j + e_j = \beta_0 + \beta_1\times 0 + e_j = \beta_0 + e_j\]</span></p>
<p>При описании гомосексуалов переменная <span class="math inline">\(orientation = 1\)</span>, тогда модель принимает вид: <span class="math display">\[s\_duration_j = \beta_0 + \beta_1\times orientation_j + e_j = \beta_0 + \beta_1\times 1 + e_j = \beta_0 + \beta_1 + e_j\]</span></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(s.duration.ms<span class="op">~</span>orientation, <span class="dt">data =</span> homo)</span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = s.duration.ms ~ orientation, data = homo)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.3357  -4.1779  -0.0343   3.7500  14.1271 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       58.466      2.735  21.375 6.41e-11 ***
## orientationhomo    5.517      3.868   1.426    0.179    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.237 on 12 degrees of freedom
## Multiple R-squared:  0.145,  Adjusted R-squared:  0.0737 
## F-statistic: 2.034 on 1 and 12 DF,  p-value: 0.1793</code></pre>
<p>Таким образом эта модель возвращает всего два числа: гетеросексуалы — <span class="math inline">\(58.466\)</span>, гомосексуалы — <span class="math inline">\(58.466+5.517=63.983\)</span>.</p>
<p><strong>ОЧЕНЬ ВАЖНО:</strong> dummy-переменных всегда (n-1). Т. е. если значений категориальной переменной 7, то dummy-переменных будет 6 и т. д.</p>
<p><strong>ОЧЕНЬ ВАЖНО:</strong> сколько бы не было значений категориальных, регрессия выбирает одну категорию (reference level) и проводит сравнение ее со всеми. Т. е. категории не в интерсепте не сравниваются, однако можно поменять reference level при помощи типа переменных <code>factor</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>homo<span class="op">$</span>orientation &lt;-<span class="st"> </span><span class="kw">factor</span>(homo<span class="op">$</span>orientation, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;homo&quot;</span>, <span class="st">&quot;hetero&quot;</span>))</span>
<span id="cb16-2"><a href="#cb16-2"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(s.duration.ms<span class="op">~</span>orientation, <span class="dt">data =</span> homo)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = s.duration.ms ~ orientation, data = homo)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.3357  -4.1779  -0.0343   3.7500  14.1271 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         63.983      2.735  23.392 2.22e-11 ***
## orientationhetero   -5.517      3.868  -1.426    0.179    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.237 on 12 degrees of freedom
## Multiple R-squared:  0.145,  Adjusted R-squared:  0.0737 
## F-statistic: 2.034 on 1 and 12 DF,  p-value: 0.1793</code></pre>
<blockquote>
<p>🤔 Скачайие датасет, который содержит <a href="https://raw.githubusercontent.com/agricolamz/2019_PhonDan/master/data/phoible_ejectives.csv">данные по количеству согласных в языках мира</a>. Постройте регрессию предсказывающую количество согласных на основании наличия абруптивных. Приведите интерсепт модели (с точностью до 4 знаков после запятой):</p>
</blockquote>
<form name="FormFour" onsubmit="return validateFormFour()" method="post">
<input type="text" name="answerFour"> <input type="submit" value="check">
</form>
<p><br></p>
<blockquote>
<p>🤔 Приведите коэффициент при переменной <code>have_ejectives</code> (с точностью до 4 знаков после запятой):</p>
</blockquote>
<form name="FormThree" onsubmit="return validateFormThree()" method="post">
<input type="text" name="answerThree"> <input type="submit" value="check">
</form>
<p><br></p>
</div>
<div id="section-3" class="section level2">
<h2>1.3 Множественная регрессия</h2>
<p>В целом, вообще-то можно в предсказании использовать не одну переменную, а сразу много. Это сложнее визуализировать, но все остальное выглядит так же:</p>
<p><span class="math display">\[y_j = \beta_0 + \beta_1 \times x_{1j} + \dots + \beta_k \times x_{kj} + e_j\]</span></p>
<ul>
<li>если вы хотите сравнивать модели, то это можно делать при помощи информационных критериев (самый распространенный — критерий Акаике, который реализован в функции <code>AIC</code>)</li>
</ul>
</div>
<div id="section-4" class="section level2">
<h2>1.4 Логистическая регрессия</h2>
</div>
<div id="section-5" class="section level2">
<h2>1.5 Регрессия со случайными эффектами</h2>
</div>
</div>
<div id="section-6" class="section level1">
<h1>2. Спектр</h1>
<audio controls>
<source src="data/Yanny_Laurel_original_speed_75.mp3" type="audio/wav">
</audio>
<p><br> <a href="https://github.com/agricolamz/2019_PhonDan/raw/master/data/Yanny_Laurel_original_speed_75.mp3">Можно скачать звук</a></p>
<p>На N+1 есть какие-то <a href="https://nplus1.ru/blog/2018/05/16/acousticdress">мои материалы</a> про это, и <a href="https://www.nytimes.com/interactive/2018/05/16/upshot/audio-clip-yanny-laurel-debate.html?fbclid=IwAR0OSchlyNl4_QnKNqhV5tZZRH1TUqE3P2WrHHSAmTzONTWGUXIHMfYzeK4">статья получше из New York Times</a>.</p>
<p>Есть еще <a href="https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.reddit.com%2Fr%2Ffunny%2Fcomments%2Fa9zlu8%2Fmay_have_just_found_next_yanni_or_laurel%2F&amp;h=AT2KHsJyiRTEbqTxneDJDGNRMBb-g2GlQYEAalu-2xACTWzZr5u_Zg1L3tzMTX0dQNKFKDjNliFhBak6cLwdTV8XHhXw9GKqwEQHWeVClq2MA5pHz6Qeyb6BIjfQag">такая история</a>, но она, видимо, не имеет непосредственного отношения к спектру.</p>
<p><a href="https://github.com/agricolamz/2019_PhonDan/raw/master/data/excellent_idea.wav">Можно скачать звук</a></p>
<script>
function validateFormOne() {
    var x = document.forms["FormOne"]["answerOne"].value;
    if (x != "77.9269") {
        alert("У меня другой ответ...");
        return false;
    } else {
        alert("Да, все правильно");
        return false;
    }
}

function validateFormTwo() {
    var x = document.forms["FormTwo"]["answerTwo"].value;
    if (x != "0.4938") {
        alert("У меня другой ответ...");
        return false;
    } else {
        alert("Да, все правильно");
        return false;
    }
}

function validateFormThree() {
    var x = document.forms["FormThree"]["answerThree"].value;
    if (x != "500.1245") {
        alert("У меня другой ответ...");
        return false;
    } else {
        alert("Да, все правильно");
        return false;
    }
}

function validateFormFour() {
    var x = document.forms["FormFour"]["answerFour"].value;
    if (x != "23.4771") {
        alert("У меня другой ответ...");
        return false;
    } else {
        alert("Да, все правильно");
        return false;
    }
}

function validateFormFive() {
    var x = document.forms["FormFive"]["answerFive"].value;
    if (x != "10.0455") {
        alert("У меня другой ответ...");
        return false;
    } else {
        alert("Да, все правильно");
        return false;
    }
}
</script>
</div>

<br><br><br>
<p><center> &copy; Г. Мороз 2019 с помощью RMarkdown. Исходный код на 
<a href="https://github.com/agricolamz/2019_PhonDan"> GitHub </a></center> </p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
